```{r}
library(ape)
library(phylobase)
library(adephylo)
library(phangorn)
library(phytools)
library(magrittr)
```

```{r}
datadir <- "150227_PANGEAsim_Regional_Train1"
gag <- read.dna(paste(datadir,"150227_HPTN071_TRAIN1_SIMULATED_gag.fa",sep="/"),format="fasta",as.matrix=TRUE)
pol <- read.dna(paste(datadir,"150227_HPTN071_TRAIN1_SIMULATED_pol.fa",sep="/"),format="fasta",as.matrix=TRUE)
env <- read.dna(paste(datadir,"150227_HPTN071_TRAIN1_SIMULATED_env.fa",sep="/"),format="fasta",as.matrix=TRUE)
s <- cbind(gag,pol,env)
sn <- row.names(s) %>% strsplit(.,"|",fixed=TRUE) %>% lapply(.,"[",1) %>% unlist
st <- row.names(s) %>% strsplit(.,"|",fixed=TRUE) %>% lapply(.,tail,1) %>% unlist %>% as.double
s2 <- s
s2.names <- row.names(s) %>% strsplit(.,"|",fixed=TRUE) %>% lapply(.,"[",1) %>% unlist
row.names(s2) <- s2.names
```

Read in trees.

```{r}
trees <- read.tree(paste(datadir,"150227_HPTN071_TRAIN1_DATEDTREE.newick",sep="/"))
numtrees <- length(trees)
```

```{r}
slist <- list()
for(i in 1:numtrees){
  tr <- trees[[i]]
  tn <- tr$tip.label
  idx <- match(tn,row.names(s))
  slist[[i]] <- s[idx,]
}
slen <- lapply(slist,dim) %>% lapply(.,"[",1) %>% unlist
```

Do simple NJ TN93

```{r}
njlist <- list()
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    dst <- dist.dna(sq,model="TN93")
    tr <- nj(dst)
    njlist[[i]] <- tr
  }else{
    njlist[[i]] <- NA
  }
}
```

```{r}
testtrees <- njlist
phdist <- list()
kfdist <- list()
for(i in 1:numtrees){
  print(i)
  tr1 <- testtrees[[i]]
  tr2 <- trees[[i]]
  if(!is.na(tr1)){
    phdist[[i]] <- dist.topo(tr1,tr2,"PH85")
    kfdist[[i]] <- dist.topo(tr1,tr2,"score")
  }else{
    phdist[[i]] <- NA
    kfdist[[i]] <- NA
  }
}
nj.phdist <- phdist
nj.kfdist <- kfdist
table(nj.phdist %>% unlist %>% na.omit %>% as.integer)
hist(nj.kfdist %>% unlist %>% na.omit %>% as.numeric)
```

FastTree.

```{r}
ftlist <- list()
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    fn <- tempfile(fileext=".fas")
    write.dna(sq,fn,format="fasta",nbcol=-1,colsep="")
    cmd <- sprintf("FastTree -nt -gtr -nosupport -quiet -nopr %s",fn)
    txt <- system(cmd,intern=TRUE)
    tr <- read.tree(text=txt)
    ftlist[[i]] <- tr
  }else{
```

```{r}
testtrees <- ftlist
phdist <- list()
kfdist <- list()
for(i in 1:numtrees){
  print(i)
  tr1 <- testtrees[[i]]
  tr2 <- trees[[i]]
  if(!is.na(tr1)){
    phdist[[i]] <- dist.topo(tr1,tr2,"PH85")
    kfdist[[i]] <- dist.topo(tr1,tr2,"score")
  }else{
    phdist[[i]] <- NA
    kfdist[[i]] <- NA
  }
}
ft.phdist <- phdist
ft.kfdist <- kfdist
table(ft.phdist %>% unlist %>% na.omit %>% as.integer)
hist(ft.kfdist %>% unlist %>% na.omit %>% as.numeric)
```

RAxML

unpartitioned

```{r}
rxlist <- list()
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    td <- tempdir()
    fn <- tempfile(tmpdir=td,fileext=".phy")
    write.dna(sq,fn,format="interleaved")
    cmd <- sprintf("raxmlHPC-PTHREADS-SSE3 -s %s -m GTRGAMMAI -n %s -T 8 -p 1 -w %s",fn,paste("u",i,sep="_"),td)
    txt <- system(cmd)
    tr <- read.tree(paste(td,"/","RAxML_bestTree.",paste("u",i,sep="_"),sep=""))
    rxlist[[i]] <- tr
    unlink(fn)
    }else{
      rxlist[[i]] <- NA
      }
 }
```

```{r}
testtrees <- rxlist
phdist <- list()
kfdist <- list()
for(i in 1:numtrees){
  print(i)
  tr1 <- testtrees[[i]]
  tr2 <- trees[[i]]
  if(!is.na(tr1)){
    phdist[[i]] <- dist.topo(tr1,tr2,"PH85")
    kfdist[[i]] <- dist.topo(tr1,tr2,"score")
  }else{
    phdist[[i]] <- NA
    kfdist[[i]] <- NA
  }
}
rx.phdist <- phdist
rx.kfdist <- kfdist
table(rx.phdist %>% unlist %>% na.omit %>% as.integer)
hist(rxp.kfdist %>% unlist %>% na.omit %>% as.numeric)
```

partitioned

```{r}
rxplist <- list()
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    td <- tempdir()
    fn <- tempfile(tmpdir=td,fileext=".phy")
    write.dna(sq,fn,format="interleaved")
    cmd <- sprintf("raxmlHPC-PTHREADS-SSE3 -s %s -m GTRGAMMAI -n %s -T 8 -p 1 -q regional_partition -w %s",fn,i,td)
    txt <- system(cmd)
    tr <- read.tree(paste(td,"/","RAxML_bestTree.",i,sep=""))
    rxplist[[i]] <- tr
    unlink(fn)
    }else{
      rxplist[[i]] <- NA
      }
 }
```

```{r}
testtrees <- rxplist
phdist <- list()
kfdist <- list()
for(i in 1:numtrees){
  print(i)
  tr1 <- testtrees[[i]]
  tr2 <- trees[[i]]
  if(!is.na(tr1)){
    phdist[[i]] <- dist.topo(tr1,tr2,"PH85")
    kfdist[[i]] <- dist.topo(tr1,tr2,"score")
  }else{
    phdist[[i]] <- NA
    kfdist[[i]] <- NA
  }
}
rxp.phdist <- phdist
rxp.kfdist <- kfdist
table(rxp.phdist %>% unlist %>% na.omit %>% as.integer)
hist(rxp.kfdist %>% unlist %>% na.omit %>% as.numeric)
```

partitioned, sep branch

```{r}
rxp2list <- list()
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    td <- tempdir()
    fn <- tempfile(tmpdir=td,fileext=".phy")
    write.dna(sq,fn,format="interleaved")
    cmd <- sprintf("raxmlHPC-PTHREADS-SSE3 -s %s -m GTRGAMMAI -n %s -T 8 -p 1 -M -q regional_partition -w %s",fn,paste("p2",i,sep="_"),td)
    txt <- system(cmd)
    tr <- read.tree(paste(td,"/","RAxML_bestTree.",paste("p2",i,sep="_"),sep=""))
    rxp2list[[i]] <- tr
    unlink(fn)
    }else{
      rxp2list[[i]] <- NA
      }
 }
```

```{r}
testtrees <- rxp2list
phdist <- list()
kfdist <- list()
for(i in 1:numtrees){
  print(i)
  tr1 <- testtrees[[i]]
  tr2 <- trees[[i]]
  if(!is.na(tr1)){
    phdist[[i]] <- dist.topo(tr1,tr2,"PH85")
    kfdist[[i]] <- dist.topo(tr1,tr2,"score")
  }else{
    phdist[[i]] <- NA
    kfdist[[i]] <- NA
  }
}
rxp2.phdist <- phdist
rxp2.kfdist <- kfdist
table(rxp2.phdist %>% unlist %>% na.omit %>% as.integer)
hist(rxp2.kfdist %>% unlist %>% na.omit %>% as.numeric)
```

PhyML

First make XML file.

```{r}
phyml.gtr <- function(runid,output.file,file.name){
phyxml <- sprintf('
<phyml runid="%s" output.file="%s">

  <topology>
    <instance id="T1" init.tree="bionj" optimise.tree="yes" search="spr"/>
  </topology>

  <branchlengths id="BL1">
    <instance id="L1" optimise.lens="yes"/>
  </branchlengths>

  <ratematrices id="RM1">
    <instance id="M1" model="GTR" optimise.rr="yes"/>
  </ratematrices>

  <equfreqs id="EF1" optimise.weights="yes">
    <instance id="F1" optimise.freq="yes"/>
  </equfreqs>

  <siterates id="SR1">
    <instance id="R1" init.value="0.0"/>
    <instance id="R2" init.value="1.0"/>
    <instance id="R3" init.value="1.0"/>
    <instance id="R4" init.value="1.0"/>
    <instance id="R5" init.value="1.0"/>
    <weights id="D1" family="gamma+inv" alpha="0.8" optimise.alpha="yes" pinv="0.4" optimise.pinv="yes">
    </weights>
  </siterates>

  <partitionelem id="partition_elem1" file.name="%s" data.type="nt" interleaved="yes" optimise.weights="yes">
    <mixtureelem list="T1, T1, T1, T1, T1"/>
    <mixtureelem list="M1, M1, M1, M1, M1"/>
    <mixtureelem list="F1, F1, F1, F1, F1"/>
    <mixtureelem list="R1, R2, R3, R4, R5"/>
    <mixtureelem list="L1, L1, L1, L1, L1"/>
  </partitionelem>

</phyml>
',runid,output.file,file.name)
    phyxml
}
phyml.partitioned <- function(runid,output.file,gag.file,pol.file,env.file){
phyxml <- sprintf('
<phyml runid="%s" output.file="%s">

  <topology>
    <instance id="T1" init.tree="bionj" optimise.tree="yes" search="spr"/>
  </topology>

  <branchlengths id="BL1">
    <instance id="L1"/>
    <instance id="L2"/>
    <instance id="L3"/>
  </branchlengths>

  <ratematrices id="RM1">
    <instance id="M1" model="GTR" optimise.rr="yes"/>
    <instance id="M2" model="GTR" optimise.rr="yes"/>
    <instance id="M3" model="GTR" optimise.rr="yes"/>
  </ratematrices>

  <equfreqs id="EF1">
    <instance id="F1" optimise.freqs="yes"/>
    <instance id="F2" optimise.freqs="yes"/>
    <instance id="F3" optimise.freqs="yes"/>
  </equfreqs>

  <siterates id="SR1">
    <instance id="R11" init.value="0.0"/>
    <instance id="R12" init.value="1.0"/>
    <instance id="R13" init.value="1.0"/>
    <instance id="R14" init.value="1.0"/>
    <instance id="R15" init.value="1.0"/>
    <weights id="D11" family="gamma+inv" alpha="0.8" optimise.alpha="yes" pinv="0.4" optimise.pinv="yes">
    </weights>
  </siterates>

  <siterates id="SR2">
    <instance id="R21" init.value="0.0"/>
    <instance id="R22" init.value="1.0"/>
    <instance id="R23" init.value="1.0"/>
    <instance id="R24" init.value="1.0"/>
    <instance id="R25" init.value="1.0"/>
    <weights id="D21" family="gamma+inv" alpha="0.8" optimise.alpha="yes" pinv="0.4" optimise.pinv="yes">
    </weights>
  </siterates>

  <siterates id="SR3">
    <instance id="R31" init.value="0.0"/>
    <instance id="R32" init.value="1.0"/>
    <instance id="R33" init.value="1.0"/>
    <instance id="R34" init.value="1.0"/>
    <instance id="R35" init.value="1.0"/>
    <weights id="D31" family="gamma+inv" alpha="0.8" optimise.alpha="yes" pinv="0.4" optimise.pinv="yes">
    </weights>
  </siterates>

  <partitionelem id="partition1" file.name="%s" data.type="nt" interleaved="yes" optimise.tree.size="yes">
    <mixtureelem list="T1, T1, T1, T1, T1"/>
    <mixtureelem list="M1, M1, M1, M1, M1"/>
    <mixtureelem list="F1, F1, F1, F1, F1"/>
    <mixtureelem list="R11, R12, R13, R14, R15"/>
    <mixtureelem list="L1, L1, L1, L1, L1"/>
  </partitionelem>

   <partitionelem id="partition2" file.name="%s" data.type="nt" interleaved="yes" optimise.tree.size="yes">
    <mixtureelem list="T1, T1, T1, T1, T1"/>
    <mixtureelem list="M2, M2, M2, M2, M2"/>
    <mixtureelem list="F2, F2, F2, F2, F2"/>
    <mixtureelem list="R21, R22, R23, R24, R25"/>
    <mixtureelem list="L1, L1, L1, L1, L1"/>
  </partitionelem>

 <partitionelem id="partition3" file.name="%s" data.type="nt" interleaved="yes" optimise.tree.size="yes">
    <mixtureelem list="T1, T1, T1, T1, T1"/>
    <mixtureelem list="M3, M3, M3, M3, M3"/>
    <mixtureelem list="F3, F3, F3, F3, F3"/>
    <mixtureelem list="R31, R32, R33, R34, R35"/>
    <mixtureelem list="L1, L1, L1, L1, L1"/>
  </partitionelem>

</phyml>
',runid,output.file,gag.file,pol.file,env.file)
    phyxml
}
```

```{r}
phymlplist <- list()
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  #sqn <- row.names(sq) %>% strsplit(.,"|",fixed=TRUE) %>% lapply(.,"[",1) %>% unlist
#row.names(sq) <- sqn
  if(slen[i]>=4){
    td <- tempdir()
    #gagfn <- tempfile(tmpdir=td,fileext="_gag.phy")
    gagfn="gag.phy"
    write.dna(sq[,1:1440],gagfn,format="interleaved")
    #polfn <- tempfile(tmpdir=td,fileext="_pol.phy")
    polfn="pol.phy"
    write.dna(sq[,1441:4284],polfn,format="interleaved")
    #envfn <- tempfile(tmpdir=td,fileext="_env.phy")
    envfn="env.phy"
    write.dna(sq[,4285:6807],envfn,format="interleaved")
    #xmlfn <- tempfile(tmpdir=td,fileext=".xml")
    xmlfn="test.xml"
    #outfn <- tempfile(tmpdir=td,fileext=".out")
    outfn="test.out"
    phyxml <- phyml.partitioned(paste("r",i,sep="_"),outfn,gagfn,polfn,envfn)
    cat(phyxml,file=xmlfn)
    cmd <- sprintf("phyml --xml=%s",xmlfn)
    txt <- system(cmd)
    tr <- read.tree(paste(outfn,"phyml_tree",sep="_"))
    phymlplist[[i]] <- tr
    #unlink(fn)
    }else{
      phymlplist[[i]] <- NA
      }
 }

```

```{r}
testtrees <- phymlplist
phdist <- list()
kfdist <- list()
for(i in 1:numtrees){
  print(i)
  tr1 <- testtrees[[i]]
  tr2 <- trees[[i]]
  if(!is.na(tr1)){
    phdist[[i]] <- dist.topo(tr1,tr2,"PH85")
    kfdist[[i]] <- dist.topo(tr1,tr2,"score")
  }else{
    phdist[[i]] <- NA
    kfdist[[i]] <- NA
  }
}
phymlp.phdist <- phdist
phymlp.kfdist <- kfdist
table(phymlp.phdist %>% unlist %>% na.omit %>% as.integer)
hist(phymlp.kfdist %>% unlist %>% na.omit %>% as.numeric)
```

Do simple ML

```{r}
mllist <- list()
mlfitlist <- list()
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    o <- pml(njlist[[i]],as.phyDat(sq),model="GTR",inv=0.01,k=4,shape=0.1)
    fit <- optim.pml(o,optNni=TRUE,optBf=TRUE,optQ=TRUE,optEdge=TRUE,optGamma=TRUE,optInv=TRUE)
    mlfitlist[[i]] <- fit
    mllist[[i]] <- fit$tree
  }else{
    mlfitlist[[i]] <- NA
    mllist[[i]] <- NA
  }
}
```

```{r}
gag.pmllist <- list()
pol.pmllist <- list()
env.pmllist <- list()
idxlist <- list()
idx <- 1
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    gag.o <- pml(unroot(rxplist[[i]]),as.phyDat(sq[,1:1440]),model="GTR",inv=0.01,k=4,shape=0.5)
    gag.pmllist[[idx]] <- gag.o
    pol.o <- pml(unroot(rxplist[[i]]),as.phyDat(sq[,1441:4284]),model="GTR",inv=0.01,k=4,shape=0.5)
    pol.pmllist[[idx]] <- pol.o
    env.o <- pml(unroot(rxplist[[i]]),as.phyDat(sq[,4285:6807]),model="GTR",inv=0.01,k=4,shape=0.5)
    env.pmllist[[idx]] <- env.o
    idxlist[[idx]] <- i
    idx <- idx+1
  }
}
```

```{r}
gag.mlfit <- pmlPart(bf+Q+inv+shape~edge,gag.pmllist)
pol.mlfit <- pmlPart(bf+Q+inv+shape~edge,pol.pmllist)
env.mlfit <- pmlPart(bf+Q+inv+shape~edge,env.pmllist)

```

```{r}
pmllist <- list()
idxlist <- list()
idx <- 1
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    o <- pml(njlist[[i]],as.phyDat(sq),model="GTR",inv=0.01,k=4,shape=0.5)
    pmllist[[idx]] <- o
    idxlist[[idx]] <- i
    idx <- idx+1
  }
}
```

```{r}
mlfit <- pmlPart(bf+Q+inv+shape~edge+nni,pmllist)
```


```{r}
pmllist <- list()
idxlist <- list()
idx <- 1
for(i in 1:numtrees){
  print(i)
  sq <- slist[[i]]
  if(slen[i]>=4){
    o <- pml(njlist[[i]],as.phyDat(sq),model="GTR",inv=0.01,k=4,shape=0.5)
    pmllist[[idx]] <- o
    idxlist[[idx]] <- i
    idx <- idx+1
  }
}
```

```{r}
mlfit <- pmlPart(bf+Q+inv+shape~edge+nni,pmllist)
```

