

This is ExaML version 3.0.10 released by Alexandros Stamatakis, Andre Aberer, and Alexey Kozlov in January 16 2014.


Alignment has 6807 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 0.00%

ExaML rapid hill-climbing mode

Using 3 distinct models/data partitions with joint branch length optimization


All free model parameters will be estimated by ExaML
ML estimate of 25 per site rate categories

Partition: 0
Alignment Patterns: 1440
Name: gag
DataType: DNA
Substitution Matrix: GTR



Partition: 1
Alignment Patterns: 2844
Name: pol
DataType: DNA
Substitution Matrix: GTR



Partition: 2
Alignment Patterns: 2523
Name: env
DataType: DNA
Substitution Matrix: GTR




ExaML was called as follows:

/usr/local/bin/examl -D -t RAxML_parsimonyTree.scD_startingtree -m PSR -s scD.binary -n scD 


Memory Saving Option: DISABLED

Best rearrangement radius: 25
ML search convergence criterion fast cycle 0->1 Relative Robinson-Foulds 0.138384
ML search convergence criterion fast cycle 1->2 Relative Robinson-Foulds 0.070131
ML search convergence criterion fast cycle 2->3 Relative Robinson-Foulds 0.045085
ML search convergence criterion fast cycle 3->4 Relative Robinson-Foulds 0.034440
ML search convergence criterion fast cycle 4->5 Relative Robinson-Foulds 0.038197
ML search convergence criterion fast cycle 5->6 Relative Robinson-Foulds 0.020038
ML search convergence criterion thorough cycle 0->1 Relative Robinson-Foulds 0.122730
ML search convergence criterion thorough cycle 1->2 Relative Robinson-Foulds 0.025047
ML search converged at thorough SPR cycle 3 with stopping criterion
Relative Robinson-Foulds (RF) distance between respective best trees after one succseful SPR cycle: 0.008140%

Likelihood of best tree: -2642429.711943


Overall Time for 1 Inference 14661.702777

Overall accumulated Time (in case of restarts): 14661.702777

Likelihood   : -2642429.711943


Model parameters written to:           /Users/sdf22/Projects/pangea-round2/examl/ExaML_modelFile.scD
Final tree written to:                 /Users/sdf22/Projects/pangea-round2/examl/ExaML_result.scD
Execution Log File written to:         /Users/sdf22/Projects/pangea-round2/examl/ExaML_log.scD
Execution information file written to: /Users/sdf22/Projects/pangea-round2/examl/ExaML_info.scD
